logging:
  level:
    root: error
    com.shadowflex.DBFiller: trace

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?stringtype=unspecified
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hidden-method:
      filter:
        enabled: true
  security:
    user.name: ${SECURITY_USER}
    user.password: ${SECURITY_PASSWORD}
  flyway:
    baselineOnMigrate: true
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?stringtype=unspecified
    user: ${DB_USER}
    password: ${DB_PASSWORD}

server:
  port: 8080


