
  name: CI
  on:
    pull_request:
        branches:
          - master
          - dev
    push: 
        branches:
          - master
          - dev
  jobs:
    flutter_test:
        name: Run flutter tests
        runs-on: ubuntu-latest
        steps: 
          - uses: actions/checkout@v2
          - uses: actions/setup-java@v1
            with:
              java-version: "12.x"
          - run: ls
          - run: cd Client
          - uses: subosito/flutter-action@v1
            with:
              channal: "stable"
          - run: flutter pub get
