
  name: CI
  on:
    pull_request:
        branches:
          - master
          - dev
    push: 
        branches:
          - master
          - dev
  jobs:
    flutter_test:
        name: Run flutter tests
        runs-on: ubuntu-latest
        env:
          working-directory: ./Client/shadow_flex
        steps: 
          - uses: actions/checkout@v2
          - uses: actions/setup-java@v1
            with:
              java-version: "12.x"
          - run: pwd
            working-directory: ${{env.working-directory}}
          - run: ls
            working-directory: ${{env.working-directory}}
          - uses: subosito/flutter-action@v1
            with:
              channal: "stable"
          - run: flutter pub get
            working-directory: ${{env.working-directory}}
          - run: flutter analyze --[no-]fatal-infos
            working-directory: ${{env.working-directory}}
          - run: flutter test
            working-directory: ${{env.working-directory}}
